# Generated by Django 3.2.5 on 2021-07-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='jobcategory',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='jobcategory',
            name='path',
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=244, unique=True),
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('rating', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=11250, null=True)),
                ('job_by', models.CharField(blank=True, max_length=255, null=True)),
                ('jobCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapper.jobcategory')),
            ],
        ),
    ]
